SPECIFIC_HEAT_CONSTANT = 75.0

LIQUID_SURFACE_AREA_MULTIPLIER = 6.0

ENVIRONMENT_TEMPERATURE = 300.0

HEAT_TRANSFER_CONSTANT = 1.0
ENVIRONMENT_HEAT_TRANSFER_COEFFICIENT = 0.1

DEFAULT_TICK_TIME = 0.01

REACTION_SPEED_MULTIPLIER = 0.01 / ENVIRONMENT_TEMPERATURE

CHEMICAL_SYSTEM_CLEAR_AMOUNT = 1e-10
