SPECIFIC_HEAT_CONSTANT = 75.0

LIQUID_SURFACE_AREA_MULTIPLIER = 6.0

ENVIRONMENT_TEMPERATURE = 300.0

HEAT_TRANSFER_CONSTANT = 1.0
ENVIRONMENT_HEAT_TRANSFER_COEFFICIENT = 0.1

MIN_REACTION_SPEED = 1e-3
REACTION_SPEED_MULTIPLIER = 0.03 / ENVIRONMENT_TEMPERATURE

DEFAULT_TICK_TIME = 0.01
CHEMICAL_SYSTEM_CLEAR_AMOUNT = 1e-10
